### ISSUE TITLE
Issue with Postleaks: No Results Returned When Searching with Postman API

### ISSUE THREAD

**Issue by dan0x1** [cosad3s/postleaks#12]
Hi, I'm using Postleaks to search for leaks related to the keyword "apikey" with the following command:

$postleaks -k apikey

The output I get is:

[*] Searching for leaks related to keyword apikey
[*] Looking for data in Postman.com
[*] Searching for requests IDs
[*] Search for requests info in collection of requests
[*] 0 results found for keyword 'apikey'. Happy (ethical) hacking!

I'm wondering if this could be related to the Postman API not functioning properly, as it seems to fail at retrieving data. Has anyone else experienced this issue? Could it be a configuration error, a problem with the tool, or something related to the connection to Postman.com?

best regards!

**Comment by Mr-koanti** [comment]
<img width="649" height="181" alt="Image" src="https://github.com/user-attachments/assets/7ce3462c-5281-4a81-9bd4-a9554dce5ae4" />

the same here no results

**Comment by dan0x1** [comment]
Hi team, update?

**Comment by cosad3s** [comment]
It should be fixed : Cloudflare was blocking some requests.

**Comment by dan0x1** [comment]
I think it still doesn't work, I tried the tool on different systems, I also ran it with vpns, etc and it still doesn't work. I don't know what the problem is.

<img width="826" height="353" alt="Image" src="https://github.com/user-attachments/assets/bf775c11-16fc-4016-ac6e-56a20f089027" />

**Comment by cosad3s** [comment]
It works on my side

<img width="656" height="185" alt="Image" src="https://github.com/user-attachments/assets/9545330e-1374-48ff-856f-9ab38de64d50" />

Can you try without any proxy or VPN and different IP address ?
Cloudflare seems to be more hardened.
